### ISSUE TITLE
Crop mode not working correctly

### ISSUE THREAD

**Issue by infinitnet** [ajaydsouza/contextual-related-posts#3]
I'm trying to use soft crop, but whether or not I tick the box "Crop mode", it neither hard nor soft crops but simply "crushes" or "stretches" the images for the thumbnails, so they look funny if the had a really wide format before. Latest WP with these settings: http://i.imgur.com/Da5fDlU.png and this is the result: http://i.imgur.com/dGd5Yzj.png (looks like this with both "Crop mode" ticked and unticked).

**Comment by ajaydsouza** [comment]
If you change the crop mode or change image sizes, you need to regenerate images because WordPress doesn't auto create images for an image size.
Please see: https://wordpress.org/plugins/regenerate-thumbnails/

**Comment by infinitnet** [comment]
Thank you for your quick response. I installed the plugin you suggested and regenerated the thumbnails after each configuration change, but the issue remains exactly as described in my bug report. Of course I cleared my browser cache as well.

**Comment by ajaydsouza** [comment]
I'm working on a new version to be released. Have you checked the latest version in this repository?

**Comment by infinitnet** [comment]
I just updated to your latest master branch, but the issue remains the same for me. Here is a full screenshot of the settings: http://i.imgur.com/uIdRhIb.png

**Comment by ajaydsouza** [comment]
Hi, I'm not sure as to why this is happening. Can you check if WordPress has created the above image in the 150x150 size?

**Comment by infinitnet** [comment]
Excuse my lack of WP experience, but what would be the path of the cropped images?

**Comment by ajaydsouza** [comment]
This would be in the same folder as your image. Images are automatically saved /wp-content/uploads by default

**Comment by infinitnet** [comment]
I assumed that and checked the folder, but it only contains the original uploaded images and no cropped versions of them. That's why I thought I might have checked the wrong folder. I doubt it's a permission problem, because uploading images works well and WP is able to create the files within the upload directory. Which part of WP or your plugin creates the cropped images and what's the approach to debug it? I should probably mention that I also tried the Timthumb setting of your module and the issue was the same.

**Comment by ajaydsouza** [comment]
The plugin doesn't crop any images automatically. It uses [add_image_size](https://codex.wordpress.org/Function_Reference/add_image_size) to register the image dimensions into WordPress and any new images are automatically cropped by WordPress on upload. If you need to create the sizes for the old image, that's where [Regenerate Thumbnails plugin](https://wordpress.org/plugins/regenerate-thumbnails/) comes into the picture. You could also try [Ajax Thumbnail Rebuild](https://wordpress.org/plugins/ajax-thumbnail-rebuild/). My personal favourite is [Force Regenerate Thumbnails](https://wordpress.org/plugins/force-regenerate-thumbnails/) but it deletes all old thumbnails, which might not be the preferred option.

You'll need to install and run this to create the thumbnails for the images that are uploaded. This does take a while to run and are usually saved in the same folder as the original image. e.g. the thumbnail would be `imagename-150x150.png`

Timthumb will no longer be available as of the next version (current beta in Github already removes support for this). In my opinion, it was the best on-the-fly option available, which unfortunately is no longer supported by the developer.

**Comment by infinitnet** [comment]
Alright, thanks a lot, I will try one of the plugins you mentioned then. I wrongly assumed that your plugin would create the cropped version of the images itself.
