### ISSUE TITLE
Caching does not differentiate between feed and web

### ISSUE THREAD

**Issue by florian-sander** [ajaydsouza/contextual-related-posts#4]
First of all: Thanks for the great plugin! :)

We've been experiencing a maddening issue, though: Every now and then crp would output the wrong number of posts and would also ignore images. Clearing the cache usually resolved the issue - until it appeared on a different post again.

I believe the root cause of this is that the caching mechanism does not differentiate between web and feed view. We had different settings for each. Now that we made sure that the settings are identical, the issue has not appeared again (yet).

**Comment by ajaydsouza** [comment]
Hi,

This might be the case. Let me see how I can differentiate and resolve this.

**Comment by ajaydsouza** [comment]
The latest commit separates out the cache related posts in feeds. This will be included in the new release of the plugin that will be out in the next week or so.

https://github.com/ajaydsouza/contextual-related-posts/commit/e27999c31ea1b3b90216147593dfd384d16fddc8

**Comment by florian-sander** [comment]
Thanks for the fix!
