### ISSUE TITLE
Thumbnail image all the same in the attachment page

### ISSUE THREAD

**Issue by zma** [ajaydsouza/contextual-related-posts#5]
The related posts' thumbnails in the attachment pages seem not correctly generated.

One example is at: http://www.fclose.com/3118/windows-7-mak-activation/win-7-activation/

All 3 related posts have the same thumbnails (the attachment) while they should not.

**Comment by ajaydsouza** [comment]
Fixed in https://github.com/ajaydsouza/contextual-related-posts/commit/7b2b486420a940470898596c770f929b1821b9ee

**Comment by zma** [comment]
Thanks @ajaydsouza ! The fix works well for me.
